[package]
name = "astra"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/xd-Abi/astra-browser/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
